dminapiVersion: v1
kind: ServiceAccount
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: fig-patcher
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: fig-patcher
    spec:
      restartPolicy: OnFailure
      serviceAccountName: fig-patcher  
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 400
      dnsPolicy: ClusterFirst
      tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists
          - effect: NoSchedule
            key: node.kubernetes.io/not-ready
            operator: Exists
      volumes:
          - name: bootstrap-info
            secret:
              secretName: bootstrap-info
              defaultMode: 420
      containers:
        - name: fig-patcher
          image: docker.io/dorbian/public-images:bootstrap
          volumeMounts:
            - name: bootstrap-info
              readOnly: true
              mountPath: /tmp/
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          command:
            - /bin/bash
            - -c
            - |
                cp /tmp/user_config.conf /root/user_config.conf
                /root/omnicluster.sh
