apiVersion: v1
kind: ServiceAccount
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fig-patcher
subjects:
  - kind: ServiceAccount
    name: fig-patcher
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fig-patcher
  namespace: kube-system
  labels:
    app: fig-patcher
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: fig-patcher
    spec:
      restartPolicy: OnFailure
      serviceAccountName: fig-patcher
      securityContext: 
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 400
      dnsPolicy: ClusterFirst
      volumes:
          - name: bootstrap-info
            secret:
              name: bootstrap-info
              defaultMode: 420
      containers:
        - name: fig-patcher
          image: docker.io/dorbian/public-images:bootstrap
          volumeMounts:
            - name: bootstrap-info
              readOnly: true
              mountPath: /root
          securityContext: 
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          command:
            - /bin/bash
            - -c
            - |
                /root/omnicluster.sh
